# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='ImageDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='ImageSubTitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
