# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170707_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='ImageDesc',
            new_name='image_description',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='ImageSubTitle',
            new_name='image_subtitle',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='ImageTitle',
            new_name='image_title',
        ),
    ]
