# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170707_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/gallery/img'),
            preserve_default=False,
        ),
    ]
